apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebhook
  template:
    metadata:
      labels:
        app: mywebhook
    spec:
      containers:
      - name: app
        args:
          - -server-cert=/tmp/tls/tls.crt
          - -server-key=/tmp/tls/tls.key
        imagePullPolicy: Always
        image: ghcr.io/mosuke5/sample-validating-admission-webhook:main
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: tls
          mountPath: /tmp/tls/
      volumes:
      - name: tls
        secret:
          secretName: mywebhook-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mywebhook
spec:
  selector:
    app: mywebhook
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
