apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "sample-validating-webhook"
webhooks:
- name: "mywebhook.mynamespace.svc.cluster.local"
  failurePolicy: Fail
  rules:
  - apiGroups: [""]
    operations: ["CREATE"]
    apiVersions: ["v1"]
    resources: ["pods"]
    scope: "Namespaced"
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjRENDQWxpZ0F3SUJBZ0lKQU1jeEtVSVcvM1F5TUEwR0NTcUdTSWIzRFFFQkJRVUFNRTR4Q3pBSkJnTlYKQkFZVEFrcFFNUTR3REFZRFZRUUlEQVZVYjJ0NWJ6RXZNQzBHQTFVRUF3d21iWGwzWldKdmIyc3ViWGx1WVcxbApjM0JoWTJVdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd3d0hoY05Nakl3TlRFM01ESTFNakl4V2hjTk1qTXdOVEUzCk1ESTFNakl4V2pCT01Rc3dDUVlEVlFRR0V3SktVREVPTUF3R0ExVUVDQXdGVkc5cmVXOHhMekF0QmdOVkJBTU0KSm0xNWQyVmliMjlyTG0xNWJtRnRaWE53WVdObExuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01JSUJJakFOQmdrcQpoa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTV6MVRvanZiWExSb3NnWk5LR0xlQjlLeThUdzNmM2QyCjI2RGlJVTRINHdadFozOFRpTlBFaDczUlR5K3ZXV0ZWV2RGY01LVkhEdjN4VUZjYWhoemh2NksreDZOeUcrUmUKZklCeEh3eDdTOXVhZUtKRitNc0QzSU84b2tBSC9GKzRMbzEzdzJzUStwUkMwNkdBVlljZWpoMDhqc2VJRlNpNwo5RzRPZkllbmJlblVuZ24wMU9URzVxNUZNVWoySFVQUkl4RmhMWUY5VWdtcWV4d1dReGVQM08xYnIwYUU5N09ICjJmSHB1a3gxcEp1Z2lPbC9QSTFJMmNlbXRCL3V2QnM2WnMrbkJLKzdNM0FtUEV4OGhCR2hONFE1OG44dHFwVmkKWmdBaTlzNUJYaHVOd3FvRlBXamZmMDZ6ZENaY3B4WDlFOUJ5cTliREJBYTBNWlpwN2N6WlNRSURBUUFCbzFFdwpUekJOQmdOVkhSRUVSakJFZ2hsdGVYZGxZbWh2YjJzdWJYbHVZVzFsYzNCaFkyVXVjM1pqZ2lkdGVYZGxZbWh2CmIyc3ViWGx1WVcxbGMzQmhZMlV1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3RFFZSktvWklodmNOQVFFRkJRQUQKZ2dFQkFITUpQSUE2Vy8xVTNRN0ZJamNkVXFBVDhOU2RLNk4xRzZNVzErblVxUkh6dEUwSmFUaWlxNzQwNlVJdApmRXAzOEg4ZVo3VzdrVE95bm5KUFNnQUVyQXgvMXhTY3ZORTFvS1d4TkZ1RlRJWUw4S3ZXU3ptV2JkSTNKNTJaCk9CYXh2UU5WWmlGQUZuYXdSR285Z0hEYllkdUltVDJDTkVIODFxcEo2UzZXSDVuNkxvb0s0N3F5aWh6TkdNZlYKRGk4SWV1cWRkTkhpQWxzNnJ3M3NreWYxQ0xzbWRhNkREb1FYaUo0MUhaTXdqNzhVSTFRR3Bsb2k2RXd4c0ZZUwpDbkpvcnNhdmticEVjRkRXdzBKNTJZOVMxT1ZyWloxNzE3WEpBeTRKV245ZjErKzJwWmhpelhvOHBSR3ZqRFNNCmpOdm5TUDZxdXJuL3p2V1JJOUtpdGhnMHVIYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      namespace: mynamespace
      name: mywebhook
      path: /runasuser-validation
  admissionReviewVersions: ["v1"]
  timeoutSeconds: 5
  sideEffects: None
